# Generated by Django 5.1.3 on 2024-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_name', models.CharField(max_length=200)),
                ('license_plate', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('passenger_capacity', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
